### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by Pheggas** [NeonOrbit/ChatHeadEnabler#1]
Hello, I spotted that when I open chat head while in landscape mode, the chat head actually doesn't open. It shows only that background darker tint but not chat.

Is this issue on messenger side or on this module's side?

**Comment by NeonOrbit** [comment]
> 
> 
> Hello, I spotted that when I open chat head while in landscape mode, the chat head actually doesn't open. It shows only that background darker tint but not chat.
> 
> Is this issue on messenger side or on this module's side?

Please send a screenshot.

**Comment by NeonOrbit** [comment]
@Pheggas   It might be due to spoofed API level. I guess I'll have to hook a specific method instead.

**Comment by Pheggas** [comment]
I recorded a video describing actually two bugs. First I shown chat head move in landscape and then that opening. 

https://streamable.com/8cl5o8

Ps: With my experience with messenger, I'd bet it's Facebook's fault. They're providing such a crappy services I can't stand it for a few years now. So, I wouldn't be surprised if it's caused by messenger version.

**Comment by NeonOrbit** [comment]
@Pheggas   Both of them are actually caused by same reason. I have a solution in mind, already working on it.

**Comment by Pheggas** [comment]
That would be epic if you could fix both of them! Really looking forward to it!

**Comment by NeonOrbit** [comment]
@Pheggas check this out, 
[ChatHeadEnabler-2.0.0beta1.zip](https://github.com/NeonOrbit/ChatHeadEnabler/files/6987408/ChatHeadEnabler-2.0.0beta1.zip)

**Comment by Pheggas** [comment]
> @Pheggas check this out,
> [ChatHeadEnabler-2.0.0beta1.zip](https://github.com/NeonOrbit/ChatHeadEnabler/files/6987408/ChatHeadEnabler-2.0.0beta1.zip)

~~I installed APK in that zip archive. Enabled it in LSPosed and then rebooted. But when i want open chat head, i navigate to "hold menu" on one of my friends but i have there "Open in bubble" and not "Open in chat head" as with your released one. Also, when i click on it, it will open chat bubble and not head so it's basically not working.~~

Messenger v325.0.0.16.118

**Needed to forceclose and reopen messenger**

Tested it in landscape and it's working correctly now!

**Comment by NeutralBit** [comment]
> **Needed to forceclose and reopen messenger**
> 
> Tested it in landscape and it's working correctly now!

you should clear Messenger app data, just in case.

**Comment by Pheggas** [comment]
> you should clear Messenger app data, just in case.

Could be. As i said, i just "restarted" that app and it started working correctly

**Comment by NeonOrbit** [comment]
> Tested it in landscape and it's working correctly now!

Good to know. I'll release a stable version soon.
