### ISSUE TITLE
android notification panel can't expand

### ISSUE THREAD

**Issue by robinsrk** [NeonOrbit/ChatHeadEnabler#10]
After using this module, i faced this strange problem that can't expand notification panel. It doesn't happen when enabling the module, but at random time. I am in android 12L custom rom. So changed almost 4-5 roms and same result. After reboot again everything works fine but after a random period of time, it happens again.

**Comment by NeonOrbit** [comment]
This module doesn't even have the permission to mess with system features in any way. Whatever it changes, stays inside the messenger app scope. I think your problem is caused by something else (could be xposed itself).

**Comment by robinsrk** [comment]
> This module doesn't even have the permission to mess with system features in any way. Whatever it changes, stays inside the messenger app scope. I think your problem is caused by something else (could be xposed itself).

Just disabled the modulrle, and everything works fine. But when i enable this module, that happens again. So i am sure that this happened after enabling the module. But don't know if it is caused by xposed or module. Can you test this module on android 12L custom roms?

**Comment by NeonOrbit** [comment]
Tested on Android 11,12,12L,13. I don't have spare phone to install custom rom right now. 
But as I said, I don't see how it could possibly interact with your notification panel. Which feature are you using? chathead or bubble? Maybe that specific messenger feature not working properly on custom rom. A video might help.

**Comment by robinsrk** [comment]
> Tested on Android 11,12,12L,13. I don't have spare phone to install custom rom right now. But as I said, I don't see how it could possibly interact with your notification panel. Which feature are you using? chathead or bubble? Maybe that specific messenger feature not working properly on custom rom. A video might help.

I am using bubble. Tried in 4-5 android 12L custom rom, all had same issue. And i will send a video regarding this problem
