### ISSUE TITLE
When someone videocall it doesn't pop-up. You need to check on the Messenger app to check who's calling 

### ISSUE THREAD

**Issue by Kaizeeen23** [NeonOrbit/ChatHeadEnabler#14]

**Comment by Kaizeeen23** [comment]
@NeonOrbit 
[Uploading LSPosed_2023-02-23T15_10_15.461289.zip…]()

**Comment by Kaizeeen23** [comment]
@NeonOrbit 
I'm using messenger version 350.0.0.7.89
[LSPosed_2023-02-23T15_10_15.461289.zip](https://github.com/NeonOrbit/ChatHeadEnabler/files/10811041/LSPosed_2023-02-23T15_10_15.461289.zip)

**Comment by NeonOrbit** [comment]
This is not ChatHeadEnabler bug. I see you are using MessengerPro module, it could from that module or from messenger itself.
