### ISSUE TITLE
Android 14 support

### ISSUE THREAD

**Issue by Loukious** [NeonOrbit/ChatHeadEnabler#15]
It seems to be crashing and causing Messenger app to reset.
![image](https://github.com/NeonOrbit/ChatHeadEnabler/assets/24696530/a24b9bea-e1ca-479a-834d-5e08c7de378c)

**Comment by NeonOrbit** [comment]
What is your messenger version?

**Comment by Loukious** [comment]
432.0.0.39.118
It's the same thing with the previous stable version as well

**Comment by NeonOrbit** [comment]
Strange, Messenger already fixed the problem with their code. I tried it on the A14 emulator, and it didn't crash at all. What ROM are you using? Have you made any modifications that might conflict with these permissions?

**Comment by Loukious** [comment]
> Strange, Messenger already fixed the problem with their code. I tried it on the A14 emulator, and it didn't crash at all. What ROM are you using? Have you made any modifications that might conflict with these permissions?

It doesn't crash all the time. At first it works fine (chat head activates successfully) but then after few minutes when someone texts me and the chat head supposed to pop up, Messenger crashes and keep crashing every time I receive a message. Disabling the module instantly fixes the issue. I'm running crDroid 14 and I have [this](https://github.com/Loukious/MessengerPro) module on.

**Comment by Yoanndp** [comment]
Hello, I created an issue [there](https://github.com/Xposed-Modules-Repo/app.neonorbit.chatheadenabler/issues/2). Do you want me to recreate it on this repository instead?

And by the way, what application are you using to catch crashes (first screenshot)? @Loukious

**Comment by Loukious** [comment]
> And by the way, what application are you using to catch crashes (first screenshot)?

I'm using [this](https://github.com/KitsunePie/AppErrorsTracking) module.

**Comment by NeonOrbit** [comment]
@Yoanndp Like I mentioned before, Messenger already dealt with this problem, so it shouldn't crash. This needs to be fixed by Messenger, not the module. But I'll still check into it.

**Comment by Yoanndp** [comment]
Alright, please keep us informed if you find something on your side. For now, I will disable and use the native bubble, as Messenger is unusable right now. I hope you will find a fix

**Comment by Loukious** [comment]
> @Yoanndp Like I mentioned before, Messenger already dealt with this problem, so it shouldn't crash. This needs to be fixed by Messenger, not the module. But I'll still check into it.

Actually you're right. At least for the first part about it being Messenger's fault not your module. Had it crash right now without having your module on (sometimes after clearing data you'd have chat heads for a while until Messenger is cleared from memory). Though I'm on latest version so doesn't seem like Facebook have fixed it at least for Android 14.

**Comment by NeonOrbit** [comment]
Looks like Messenger adapted to ``FOREGROUND_SERVICE_SPECIAL_USE`` in the latest version (v435). This should solve the issue, I couldn't reproduce the crash after many tries. Can any of you confirm it?

**Comment by Loukious** [comment]
> Looks like Messenger adapted to `FOREGROUND_SERVICE_SPECIAL_USE` in the latest version (v435). This should solve the issue, I couldn't reproduce the crash after many tries. Can any of you confirm it?

Seems to be working fine now. Thank you for your time.

**Comment by Loukious** [comment]
Can someone confirm whether the microphone is being properly detected while sending a voice message in chat head?

**Comment by Yoanndp** [comment]
> Can someone confirm whether the microphone is being properly detected while sending a voice message in chat head? 

I just tried right now, and it works
