### ISSUE TITLE
[Messenger-Bug] Chat head doesn't appear on new message

### ISSUE THREAD

**Issue by Pheggas** [NeonOrbit/ChatHeadEnabler#3]
Hello. I don't know if it is caused by my ROM but my chat heads doesn't appear to have new messages for me.

Example: When someone writes me a message, chat head doesn't appears from that person.

Ps: On Xiaomi Mi 9T with Xiaomi.eu ROM 12.1.2

**Comment by NeonOrbit** [comment]
1. Are you able to open chat head manually?
2. Do you receive message notification?
3. If you disable the module, does bubble appears when there's a new message?

**Comment by Pheggas** [comment]
1. Yes
2. I do
3. Yes

But I'm not able to replicate it right now as I updated Riru and LSPosed to latest version and now, LSPosed crashes on every open. I don't really know what to do with it but I guess I should downgrade the Riru version again. But that's not the point of this issue, nor this project.

**Comment by NeonOrbit** [comment]
I saw a lot of people complaining about the same problem, so I guess this is a bug from messenger side.

**Comment by Pheggas** [comment]
Oh. I'm glad I'm not alone lol 😁
Ps: If someone have version that doesn't have this bug, let me know 😊

**Comment by NeonOrbit** [comment]
I'll :-)
