### ISSUE TITLE
Chat head failed to hook

### ISSUE THREAD

**Issue by bobydj** [NeonOrbit/ChatHeadEnabler#4]
Please fix the current version Facebook messenger. Its several times in a day a pop up message show up that chat head failed to hook

**Comment by NeonOrbit** [comment]
Install [latest ](https://github.com/NeonOrbit/ChatHeadEnabler/releases/latest) version.

**Comment by bobydj** [comment]
Already in 2.2.1 version

**Comment by NeonOrbit** [comment]
Send log from LSPosed/Edxposed.

**Comment by bobydj** [comment]
Uploaded in attachment.. Please check any error may found

**Comment by NeonOrbit** [comment]
There's no attachment. You should open github and send log as a comment.

**Comment by bobydj** [comment]
![Screenshot_2021-11-16-15-02-47-721_com android shell](https://user-images.githubusercontent.com/81475046/141955109-0c2bfba5-2d2c-455f-ab63-a863f1da78fb.jpg)
![Screenshot_2021-11-16-15-02-52-202_com android shell](https://user-images.githubusercontent.com/81475046/141955120-98d7ec85-94b8-41a9-93c0-280942eb831b.jpg)
![Screenshot_2021-11-16-15-02-56-024_com android shell](https://user-images.githubusercontent.com/81475046/141955132-bf777abc-9881-446d-ad9b-ef3b07119417.jpg)
![Screenshot_2021-11-16-15-02-59-487_com android shell](https://user-images.githubusercontent.com/81475046/141955145-6175467d-533e-4835-9501-020e56b0cede.jpg)

**Comment by NeonOrbit** [comment]
Thanks. I need to know your messenger version.

**Comment by bobydj** [comment]
![Uploading Screenshot_2021-11-16-14-31-55-365_com.miui.securitycenter.jpg…]()

**Comment by bobydj** [comment]
![Uploading Screenshot_2021-11-16-14-31-55-365_com.miui.securitycenter.jpg…]()

**Comment by bobydj** [comment]
Messenger version 338.1.0.11.117

**Comment by NeonOrbit** [comment]
Are you using the official version from playstore? If so, send me it's apk. 

Use `Amaze File Manger` to extract the apk. 

Or termux: `su -c pm path com.facebook.orca | cp $(awk -F':' '{print $2}') /sdcard/­messenger.apk`

Or adb: `adb shell "pm path com.facebook.orca | cp $(awk -F':' '{print $2}') sdcard/messenger.apk"`

**Comment by bobydj** [comment]
Here

**Comment by bobydj** [comment]
I uploaded it in drive 

https://drive.google.com/file/d/12sXmIazFW30ABr6yrZh6_Y0Ir1CEhMjO/view?usp=drivesdk

**Comment by NeonOrbit** [comment]
I checked your apk, it's working properly.

**Comment by bobydj** [comment]
Now ok..

![Screenshot_2021-11-17-10-18-06-390_com android shell](https://user-images.githubusercontent.com/81475046/142134019-e112354e-6d00-4c45-8e39-45fec8ac9852.jpg)

**Comment by NeonOrbit** [comment]
Is it working with v2.2.1 now?

**Comment by bobydj** [comment]
Yes now it works without any issues
