### ISSUE TITLE
Request: Get bubbles in messemger

### ISSUE THREAD

**Issue by robinsrk** [NeonOrbit/ChatHeadEnabler#5]
Please make a module that can be used to get chat bubbles instead of chat head. I am on android 12 but messenger is letting me use the old chat head which i don't like.

**Comment by NeonOrbit** [comment]
Install this.
[~~ChatHeadEnabler-v2.2.2-dev.4r.zip~~]

> Enable in LSPosed 
> Restart Messenger
> Open chat head

Send LSPosed log.

**Comment by alexhulbert** [comment]
Hi, I'd also like this feature. I tested the zip you sent with various old versions of Messenger (328, 335, 339, 350), but none of them worked. Would it be possible to make an upgraded zip based off the most recent release of this repo? I'd be happy to provide logs or help in any other way.

**Comment by NeonOrbit** [comment]
@alexhulbert This feature is already in development. You can use this beta for now, 
[~~ChatHeadEnabler-v2.4.0-bubble.zip~~]

Stable version will be released soon.

**Comment by alexhulbert** [comment]
Thanks so much! This works perfectly!

**Comment by NeonOrbit** [comment]
@alexhulbert hey, does your messenger have a settings tab at the bottom?

**Comment by alexhulbert** [comment]
@NeonOrbit No it doesn't, just Chats, Calls, People, and Stories

**Comment by NeonOrbit** [comment]
oh okay, thanks.

**Comment by peetereczek** [comment]
Looks like it's working on Android 12.1 with Magisk 25.2 and LSPosed 1.8.4 (zygisk). Thank you!

**Comment by NeonOrbit** [comment]
Uploaded a stable version now, [check here](https://github.com/NeonOrbit/ChatHeadEnabler/releases/latest).
