### ISSUE TITLE
MIUI notification style

### ISSUE THREAD

**Issue by markpollente** [NeonOrbit/ChatHeadEnabler#7]
Hi, this is fantastic btw. Just a minor issue, this module forces messenger to have the android notification style instead of the MIUI one. 

![IMG_20220721_145810](https://user-images.githubusercontent.com/5819641/180150717-08afb53c-edd8-4bb0-8b41-e5cf0b58ecd6.jpg)

As shown here, messenger has the Android notification style while the Security app has the MIUI notification style.

**Comment by NeonOrbit** [comment]
It doesn't force anything, this is the default style.
