### ISSUE TITLE
I can't installed the app 

### ISSUE THREAD

**Issue by ChacalyYakarta** [NeonOrbit/ChatHeadEnabler#8]
When it finished downloading when I tried to install it gives me error

**Comment by NeonOrbit** [comment]
What was the error exactly? and what is your android version?

**Comment by ChacalyYakarta** [comment]
I just read it's on Android 11 or higher i have android 10

**Comment by ChacalyYakarta** [comment]
It says there was a problem while parsing the package

**Comment by NeonOrbit** [comment]
> It says there was a problem while parsing the package

It's for Android 11+ devices.
